platform :ios, '7.0' 

link_with [:Sample, :Tests]
pod 'SHGestureRecognizerBlocks', :path => '../'

target :Sample, :exclusive => true do
pod 'SHKeyValueObserverBlocks'
pod 'SHSegueBlocks'

end

target :Tests, :exclusive => true do
  pod 'SHTestCaseAdditions'
  pod "KIF/XCTest", :git => "https://github.com/tonyd256/KIF", :branch => "xctest"
end



